name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Replace GA Tracking ID
        run: |
          if [ -n "${{ secrets.GA_TRACKING_ID }}" ]; then
            sed -i 's/__GA_TRACKING_ID__/${{ secrets.GA_TRACKING_ID }}/g' index.html
          else
            echo "GA_TRACKING_ID secret is not set. Removing GA tracking code."
            sed -i '/<!-- GA_TRACKING_BLOCK_START -->/,/<!-- GA_TRACKING_BLOCK_END -->/d' index.html
          fi
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
